dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
before_script: composer install
env:
  - PHRETS_TESTING_USERNAME=fake PHRETS_TESTING_PASSWORD=fake
script: vendor/bin/phpunit --coverage-text
